version: "3.9"

services:
  db_service:
    build: ./db_service
    container_name: db_service
    ports:
      - "5001:5001"
    tty: true
    volumes:
      - db_data:/app/data
    networks:
      - app_network

  email_service:
    build: ./email_service
    container_name: email_service
    ports:
      - "5002:5002"
    tty: true
    depends_on:
      - db_service
    networks:
      - app_network

  ui_service:
    build: ./ui_service
    container_name: ui_service
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    depends_on:
      - db_service
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data: